#!/bin/env python3

import sys
from readers import *
from filters import *

rd = ReaderBin("data/random.bin", 16, "le", [8, 7, 6, 5, 4, 3, 2, 1, 0])
#rd = ReaderCSV("data/data_osc.csv", [1, 2])
#rd = ReaderCSV("data/tp402-zcd5_fix.csv", [0, 1, 2])

st = FilterAmpStats(rd)

sys.exit(0)

print(ds.peek(2))

for i in range(0, ds.get_row_count()):
    print(ds.get_row_num(), ":", ds.read())

# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4
